#!/bin/sh

HAPP=houseclock

case $1 in
    configure|abort-upgrade|abort-deconfigure|abort-remove)
        grep -q '^house:' /etc/passwd || useradd -r house -s /usr/sbin/nologin -d /var/lib/house
        systemctl daemon-reload
        systemctl enable $HAPP
        systemctl start $HAPP
        ;;
esac

